baseURL = "/"
title = "My Portfolio Title"
theme = "PaperMod"

# Theme configuration
[params]
env = "production"
author = "<author>"
description = "Portfolio description"
keywords = ["Blog", "Portfolio", "PaperMod"]
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableScrollToTop = false

[params.label]
text = "Home"
icon = "/profile_.png"
iconHeight = 24

[params.profileMode]
enabled = true
title = "Caden Hinckley"
subtitle = "Computer Science"
imageUrl = "profile.png"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "tags"
url = "/tags/"



[[params.socialIcons]]
name = "github"
url = "https://github.com/"

[[params.socialIcons]]
name = "Linkedin"
url = "https://www.linkedin.com/in/caden-hinckley-49a145224/"


[[menu.main]]
identifier = "About Me"
name = "About Me"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "Projects and Education"
name = "Projects and Education"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "github"
name = "My Github"
url = "https://github.com/hinckleyc?tab=repositories"
weight = 30

[[menu.main]]
identifier = "Linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/caden-hinckley-49a145224/"
weight = 30
